# Generated by Django 2.0.2 on 2018-02-21 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published')),
                ('author', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Changelog Posts',
            },
        ),
    ]
