# Generated by Django 2.2.1 on 2019-05-09 09:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fach', 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Name des Fachs'),
        ),
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.FileField(upload_to='Tasks/%Y/%m', verbose_name='Dateipfad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(13), django.core.validators.MinValueValidator(1)], verbose_name='Klassenstufe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userinterface.Subject', verbose_name='Fach'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=255, verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Lehrer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen'),
        ),
    ]
