# Generated by Django 2.2.5 on 2019-09-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0003_auto_20190711_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255, verbose_name='Tag')),
                ('tag_color', models.CharField(max_length=6, verbose_name='Farbe')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinterface.Tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinterface.Task')),
            ],
        ),
    ]
