# Generated by Django 2.2.5 on 2019-09-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0004_tag_tasktags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tasktags',
            options={'verbose_name': 'Task - Tag', 'verbose_name_plural': 'Task - Tags'},
        ),
    ]
