# Generated by Django 2.2.5 on 2019-09-25 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0005_auto_20190925_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Klassenstufe'),
        ),
    ]
