# Generated by Django 2.2.6 on 2019-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0006_auto_20190925_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(max_length=6, null=True, verbose_name='Farbe'),
        ),
    ]
