# Generated by Django 2.0.2 on 2018-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('uploadDate', models.DateTimeField(verbose_name='Date published')),
                ('dataPath', models.CharField(max_length=255)),
                ('thumbnailPath', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Aufgaben',
            },
        ),
    ]
