# Generated by Django 2.0.2 on 2018-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0002_auto_20180214_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dataPath',
        ),
        migrations.AddField(
            model_name='task',
            name='docfile',
            field=models.FileField(default='a', upload_to='documents/%Y/%m/%d'),
        ),
    ]
