# Generated by Django 2.0.2 on 2018-02-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0003_auto_20180220_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
