# Generated by Django 2.0.2 on 2018-02-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0005_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
