# Generated by Django 2.0.2 on 2018-02-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0007_auto_20180220_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uploadDate',
        ),
    ]
