# Generated by Django 2.0.2 on 2018-02-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0008_remove_task_uploaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uploaddate',
            field=models.DateTimeField(default='02.02.2012', verbose_name='Date published'),
        ),
    ]
