# Generated by Django 2.0.2 on 2018-02-20 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0010_auto_20180221_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uploaddate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published'),
        ),
    ]
