# Generated by Django 2.0.2 on 2018-02-20 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0011_auto_20180221_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uploaddate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 0, 15, 14, 317113), verbose_name='Date published'),
        ),
    ]
