# Generated by Django 2.0.2 on 2018-02-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0012_auto_20180221_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uploaddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am'),
        ),
    ]
