# Generated by Django 2.0.2 on 2018-02-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0013_auto_20180221_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uploaddate',
            field=models.DateTimeField(verbose_name='Hochgeladen am'),
        ),
    ]
