# Generated by Django 2.0.2 on 2018-02-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlasUpload', '0014_auto_20180221_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
