# Generated by Django 2.0.2 on 2018-02-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atlasUpload', '0015_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabenname', models.CharField(max_length=255)),
                ('lehrer', models.CharField(max_length=255)),
                ('uploaddate', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('docfile', models.FileField(upload_to='tasks/%Y/%m')),
                ('thumbnailPath', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Aufgaben',
            },
        ),
    ]
