# Generated by Django 2.0.2 on 2018-02-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clpost',
            new_name='ChangelogPost',
        ),
    ]
