# Generated by Django 2.0.2 on 2018-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_auto_20180207_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelogpost',
            options={'verbose_name_plural': 'Changelog Posts'},
        ),
        migrations.AlterField(
            model_name='changelogpost',
            name='date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
