# Generated by Django 2.0.2 on 2018-03-17 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('lehrer', models.CharField(max_length=255)),
                ('datum', models.DateTimeField(default=datetime.datetime.now, verbose_name='Hochgeladen am')),
                ('datensatz', models.FileField(upload_to='Aufgaben/%Y/%m')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='atlas.Tag'),
        ),
    ]
