# Generated by Django 2.0.2 on 2018-03-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='tags',
        ),
    ]
