# Generated by Django 2.0.2 on 2018-02-21 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('lehrer', models.CharField(max_length=255)),
                ('datum', models.DateTimeField(default=datetime.datetime.now, verbose_name='Hochgeladen am')),
                ('datensatz', models.FileField(upload_to='Aufgaben/%Y/%m')),
            ],
            options={
                'verbose_name_plural': 'Aufgaben',
            },
        ),
    ]
