# Generated by Django 2.0.2 on 2018-03-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
