# Generated by Django 2.0.2 on 2018-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180310_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='upload.Tag'),
        ),
    ]
