# Generated by Django 2.0.2 on 2018-03-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_aufgabe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabe',
            options={'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
