# Generated by Django 2.0.2 on 2018-03-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
